---
apiVersion: v1
kind: Service
metadata:
      name: locust
spec:
  type: ClusterIP
  selector:
    app: locust
  ports:
  - name: webui
    port: 80
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
spec:
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "true"
    spec:
      containers:
        - name: locustloadgen
          image: javier1/px-locust:0.3
          env:
          - name: FRONTEND_ADDR
            value: "http://frontend:80"
---
apiVersion: v1
kind: Service
metadata:
    name: locust-external
spec:
  type: LoadBalancer
  selector:
    app: locust
  ports:
  - name: http
    port: 80
    targetPort: 5000
---
